### ISSUE TITLE
How to change the console options

### ISSUE THREAD

**Issue by ohadln** [paralin/SkiffOS#25] opened 2017-05-21 07:11 UTC
Hi, working with SkiffOS in a VM(VMWare / Virtualbox) I want to redirect the console to a file on the host via serial port. How do I change the console options?

Thanks in advance,
Ohad

**Comment by paralin** [comment] 2017-05-21 07:12
Hi @ohadln

The system uses systemd-journald at the moment. You can customise this using the standard systemd-journald config files in a rpot

**Comment by paralin** [comment] 2017-05-23 21:39
If you actually want to redirect the entire console, you need to change the kernel arguments and add a `console=/dev/myTTY0,115200`, if you're using Grub this will be in the grub config.

**Comment by ohadln** [comment] 2017-05-26 11:35
Hi Christian, 

Thanks Christian, I know about this option, however, not sure where to put it. Is there an option in the kernel for that or do I add it with root_overlay or post_build script(replacing /boot/grub/grub.cfg)?

Thanks,
Ohad

**Comment by paralin** [comment] 2017-05-26 17:30
How are you making the grub cfg and installing grub right now? I'll bundle all of this into an example.

**Comment by paralin** [comment] 2017-05-29 02:49
Am happy to help here with this more, I'm working on a vagrant example right now. Feel free to comment if you want me to re-open.

**Comment by ohadln** [comment] 2017-06-01 09:54
Added the following inside configs/intel/x64/kernel/grub:

GRUB_CMDLINE_LINUX_DEFAULT="quiet" 
GRUB_CMDLINE_LINUX="console=tty0 console=ttyS0,115200"
GRUB_TERMINAL=serial console
GRUB_SERIAL_COMMAND="serial --unit=0 --speed=115200 --stop=1"

However, doesn't see to output the console logs to the serial console(serial console configured on VirtualBox and redirected to a file).

**Comment by paralin** [comment] 2017-06-02 21:36
I'll try to reproduce this when working on the vagrant example. I've been busy re-writing skiff-core in the last week or so. By the way - if you're using it, let me know what you think of the new version, it's a complete rewrite.

**Comment by paralin** [comment] 2017-06-05 23:39
@ohadln configs/intel/x64/kernel/grub - the "kernel" directory inside a config is intended for kernel config fragments, that is for the kernel. Afaik specifying GRUB configurations here won't do anything. You need to override wherever you generate the grub.cfg.

**Closed** 2017-08-13 21:59 UTC
Labels: question
